CREATE TABLE branch (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(20) NOT NULL UNIQUE,
  name VARCHAR(120) NOT NULL,
  address VARCHAR(255) NOT NULL
);

CREATE TABLE financial_product (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(20) NOT NULL UNIQUE,
  name VARCHAR(120) NOT NULL,
  type VARCHAR(20) NOT NULL
);

CREATE TABLE transaction_record (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tx_date DATE NOT NULL,
  branch_id BIGINT,
  product_id BIGINT,
  raw_branch_code VARCHAR(20) NOT NULL,
  raw_product_code VARCHAR(20) NOT NULL,
  amount NUMERIC(18,2) NOT NULL,
  tx_type VARCHAR(20) NOT NULL,
  status VARCHAR(20) NOT NULL,
  rejection_reason VARCHAR(255),
  created_at TIMESTAMP NOT NULL,
  CONSTRAINT fk_tx_branch FOREIGN KEY (branch_id) REFERENCES branch(id),
  CONSTRAINT fk_tx_product FOREIGN KEY (product_id) REFERENCES financial_product(id)
);

CREATE TABLE daily_close (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  close_date DATE NOT NULL,
  branch_id BIGINT NOT NULL,
  product_id BIGINT NOT NULL,
  total_income NUMERIC(18,2) NOT NULL,
  total_expense NUMERIC(18,2) NOT NULL,
  net_total NUMERIC(18,2) NOT NULL,
  tx_count BIGINT NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  CONSTRAINT fk_dc_branch FOREIGN KEY (branch_id) REFERENCES branch(id),
  CONSTRAINT fk_dc_product FOREIGN KEY (product_id) REFERENCES financial_product(id),
  CONSTRAINT uk_daily_close UNIQUE (close_date, branch_id, product_id)
);

CREATE INDEX idx_transaction_record_tx_date_status ON transaction_record(tx_date, status);
CREATE INDEX idx_transaction_record_branch_tx_date ON transaction_record(branch_id, tx_date);
CREATE INDEX idx_transaction_record_product_tx_date ON transaction_record(product_id, tx_date);
CREATE INDEX idx_transaction_record_raw_codes ON transaction_record(raw_branch_code, raw_product_code);
CREATE INDEX idx_daily_close_date ON daily_close(close_date);
